- hosts: all
  become: yes
  tasks:
    - name: Обновить кэш пакетов
      apt:
        update_cache: yes

    - name: Установить Apache
      apt:
        name: apache2
        state: present

    - name: Убедиться, что Apache запущен
      service:
        name: apache2
        state: started
        enabled: true
    - name: Скачать index.html
      copy:
        src: "index.html"
        dest: /var/www/html/
